
- name: install default apache server
  hosts: all
  become: yes
  tasks:
  - name: install apache
    apt: name=apache2 state=present
  
  - name: start apache server
    service: name=apache2 state=started enabled=yes